### ISSUE TITLE
Installation methods (parts of `setup.py` job are done by `soundcraft_dbus_service --setup`)

### ISSUE THREAD

**Issue by ndim** [lack/soundcraft-utils#9] opened 2020-08-15 20:55 UTC
The normal package build stages are:

  1. build stage: 
     Build files by compiling, generating them from template files, etc. pp.

  2. install stage: 
     Install the built files to staging area, without building them.

  3. Binary packaging stage: 
     Put all the files from staging area into a binary package.

Trying this with `soundcraft-utils`:

  1. `python setup.py build`

  2. `python setup.py install --skip-build`

     After this, we are still missing some files which need to be both built/generated and installed: The `dbus-1` and `xdg` files.

  3. Now we are supposed to run `soundcraft_dbus_service --setup` which then builds some files, installs them, and then calls some external programs on them.

Why not build those files at the `pythonsetup.py build` stage and
install them at the `python setup.py install` stage? Then the
`soundcraft_dbus_service --setup` part would not be needed any more,
and the normal build/install/uninstall steps would work normally.

What am I missing here?

Partially related: If the build/install stages have been moved from
`soundcraft_dbus_service --setup` to `setup.py`, all `data/**` files
from the packages are not needed after installation any more and can
thus be removed from the Python package. The one exception appears to
be the `*.png` file which is used by `soundcraft_gui`.

Also partially related: The names of the `xdg` and `dbus-1` files
installed by `soundcraft_dbus_service --setup` are not using a FQDN
based names. Some other programs (e.g. quodlibet) use a github based
FQDN, so `io.github.soundcraft-utils.*.{desktop,png,svg}` could be a
good namespace for this.

**Comment by lack** [comment] 2020-08-16 18:08
The thing that's missing here is that setup.py doesn't (and shouldn't) let you install files to absolute paths (at least not that I've figured out so far).  This is I believe by design, because pypi packages are designed to work in system-wide installations (where theoretically this would be okay) but also in sandbox modes like `virtualenv` and `pip --user` where it wouldn't be practical, possible, or correct to have access to /var/lib /usr/share and the like.

Maybe this means that pypi is a bad way to distribute software like this.  Perhaps it is.  I'm not married to it being the main distribution medium for this software, and would welcome other/better/alternative ways to do it.  But as long as it's what I'm using, having a separate `--setup` step to affect the base OS configuration was the pragmatic approach I've landed on thus far.

I'm glad to consider other mechanisms for distribution or installation, and maybe some of it would be come easier after addressing some of the suggestions you raise in issue #8 

(Secondary issue: FQDN-based names - Sure, I think this is a good suggestion.  I'll put it on the TODO list)

**Comment by ndim** [comment] 2020-08-19 03:37
Apropos FQDN-based names: As those names are part of the DBUS API and will thus be quite permanent, perhaps creating a github project for `soundcraft-utils` would be a good idea, so that the FQDN used could be `soundcraft-utils.github.io` instead of `lack.github.io`.

**Comment by ndim** [comment] 2020-08-21 07:31
I have experimented and read a bit with setuptools and xdg and dbus configuration. So I have gathered a few ideas on how `soundcraft-utils` can be installed.

AFAICT, a pure Python package works fine with what `setup.py` with `setuptools.setup()` do by default.

However, `soundcraft-utils` has been designed to interface with system components which are outside of a pure Python package's scope:

  * `soundcraft_dbus_service` DBUS service
  * XDG desktop file and icon for desktop integration of the `soundcraft_gui` GUI app

Both DBUS and XDG desktop expect their files in well-known locations outside of the system-wide `/usr/local/bin` and `/usr/local/lib/python3.8/site-packages/` or their respective equivalents in `$HOME/.local/` for `--user` installations. So needing to extend `setup.py` a bit to support DBUS and XDG is not a very far fetched need.

There are basically two different kinds of installations for normal pure Python packages: The `--user` installation and the system wide installation.

  * A system wide installation will install into places like
      * `/usr/local/bin/` for the scripts
      * `/usr/local/lib/python3.8/site-packages/` for the Python modules
      * `/usr/local/share/applications/` for the XDG `.desktop` file
      * `/usr/share/icons/` for the XDG icon files
      * `/usr/share/dbus-1/` for the DBUS configuration files for running the dbus service as root
      * `/var/lib/soundcraft-utils/` for the dbus service state

  * A `--user` installation will install into places like
      * `$HOME/.local/bin/` for the scripts
      * `$HOME/.local/lib/python3.8/site-packages/` for the Python modules
      * `$HOME/.local/share/applications/` for the XDG `.desktop` file
      * `$HOME/.local/share/icons/` for the XDG icon files
      * `???` for the DBUS configuration files for running the dbus service *as root*
      * `???` for the dbus service state

Uhm. Not sure how to support the `--user` installation with a DBUS service running as root, or if that is to be desired at all. The current method of running `soundcraft_dbus_service --setup` as root does not help here much either.

One solution for `--user` installations could be to have the DBUS service running as that non-root user. This of course means that the `/dev/bus/usb/NNN/MMM` device permissions would need to be set up using udev rules such that the dbus service can actually access the device. This `--user` installation would lose the feature of the dbus service keeping state across different users, but for a single user, it would all work as intended -- as long as people have once set up a udev rule for the device permissions.

In that case, for a `--user` installation we would install a different DBUS `.service` file which has the `User=root` of the system-wide dbus service configuration replaced with something consistent with running the service as the user.

This would allow complete removal of the `soundcraft_dbus_service --setup` and `soundcraft_dbus_service --uninstall` functionality from both the dbus service, and from the whole `soundcraft` Python module package.

Also, there is no way around at least once being root when you want to run `soundcraft-utils`: Either you need root for a system wide installation with a dbus service running as root, or you need root to install a udev rule for device permission setup and have everything running as a non-root user.

I think supporting both a system wide install and a per-user install from `setup.py` would cover

  * casual users installing `soundcraft-utils` from github and updating it regularly (--user install)
  * heavy users and developers installing `soundcraft-utils` from github and updating it regularly (--user install)
  * distribution packages installing `soundcraft-utils` system wide

One slight remaining issue might be what happens when the distribution package is so old that one user wants to run a `--user` install from an up to date github source: There would now be a system wide `soundcraft_dbus_service` and a per-user `soundcraft_dbus_service`, and somehow when that one user run their own `soundcraft_dbus_service`, their applications should reach their own instance, not the system wide one. Also, when simultaneously other users use the system wide dbus service, or the service from their own sources... I am feeling a headache coming on. Perhaps better just not support that at all?

**Comment by ndim** [comment] 2020-08-21 08:27
If the dbus service has been made to run as a non-root user for the `--user` installations, then distribution packages should be able to relatively easily chose to run the system-wide dbus service as a non-root `soundcraft-utils` per-package user, as long as the distribution package also sets up the device permissions for the `soundcraft-utils` .

**Comment by ndim** [comment] 2020-08-24 14:59
I have read up a bit on pip, virtualenv and venv, and it looks to me that the distinction to make is *not* between an installation using `setup.py install` versus `setup.py install --user`.

The two main classes of installations are:

  * root installations or system-wide installations
    Where executable files, library files, and configuration files are installed as root, and the dbus service can run as root, or maybe as a dedicated non-root user.

  * non-root installations or local installations
    Where executable files, library files, and configuration files are installed as non-root user can run as that non-root user.

Whether that non-root installation happens through `setup.py install --user`, or `pip install -e path/to/soundcraft-utils`, or with pip running inside a venv or virtualenv environment... from an operating system point, all of those have in common that all the processes run as a non-root user. Whether the python executable is in /usr/bin or in /path/to/my-venv/bin does not matter, or what environment variables it uses to find where the python libraries are located.

Any in-between installations with python files installed as non-root user and the dbus service running as root is a very thinly disguised priviledge escalation.

At this time, I am researching into setuptools for how to adapt `setup.py` so that `pip install` will install the proper

  * python package (solved by default setuptools)
  * python scripts (partially solved by default setuptools)
  * dbus config files (bus activation for non-system dbus bus activation is a bit underdocumented)
  * xdg config files (install desktop file and icon(s) into `$HOME/.local/share` or `/usr/share` `applications/` and `icons/hicolor/`)

in the proper places.

I am not pursuing the path of in-between installations any more, as there is no way to solve the priviledge escalation issue created by running python code a non-root can modify at will as a root process.

**Comment by lack** [comment] 2021-07-02 10:41
Fixed in https://github.com/socratools/socranop/pull/4

**Closed as completed by lack** 2021-07-02 10:41 UTC
